<?php

return [
    'employee_type' => [
        'employee' => 'employee',
        'contractor' => 'contractor',
    ],
    'loe_type' => [
        'Junior' => 'Junior',
        'Normal' => 'Normal',
        'Senior' => 'Senior',
    ],
    'region' => [
        'Europe' => 'Europe',
        'MEA' => 'MEA',
        'NAM' => 'NAM',
        'LATAM' => 'LATAM',
        'APAC' => 'APAC',
    ],
    'job_role' => [
        'ASC' => 'ASC',
        'ISC' => 'ISC',
    ],
    'domain-users' => [
        '' => '',
        'APM' => 'APM',
        'Security' => 'Security',
        'SDLAN' => 'SDLAN',
        'SDWAN' => 'SDWAN',
        'UC' => 'UC',
        'CC' => 'CC',
        'SMS' => 'SMS',
        'DD' => 'DD',
    ],
    'domain-projects' => [
        'Hybrid Security' => 'Hybrid Security',
        'Hybrid APM' => 'Hybrid APM',
        'Hybrid Network' => 'Hybrid Network',
        'UC' => 'UC',
    ],
    'meta_activity' => [
        'BILLABLE' => 'BILLABLE',
        'ABS' => 'ABS',
        'OTHER' => 'OTHER',
        'CF' => 'CF',
    ],
    'project_status' => [
        'Pipeline' => 'Pipeline',
        'Started' => 'Started',
        'Closed' => 'Closed',
    ],
    'project_type' => [
        'Baseline' => 'Baseline',
        'Project' => 'Project',
        'Pre-sales' => 'Pre-sales',
        'Orange absence or other' => 'Orange absence or other',
    ],
    'project_subtype' => [
        'POC' => 'POC',
        'Assessment' => 'Assessment',
        'Pilot' => 'Pilot',
        'Build/Run' => 'Build/Run',
        'Recurring consulting' => 'Recurring consulting',
        'OpenLab' => 'OpenLab',
    ],
    'samba_stage' => [
        '1 Pre-Qualification' => '1 Pre-Qualification',
        '2 Qualification' => '2 Qualification',
        '3 Proposal' => '3 Proposal',
        '4 Negotiation' => '4 Negotiation',
        '5 Handover' => '5 Handover',
        'Closed Cancelled' => 'Closed Cancelled',
        'Closed Duplicate' => 'Closed Duplicate',
        'Closed Lost' => 'Closed Lost',
        'Closed Won' => 'Closed Won',
    ],
    'activity_type' => [
        'ISC' => 'ISC',
        'ASC' => 'ASC',
    ],
    'year' => [
        '2015' => '2015',
        '2016' => '2016',
        '2017' => '2017',
        '2018' => '2018',
        '2019' => '2019',
        '2020' => '2020',
        '2021' => '2021',
        '2022' => '2022',
        '2023' => '2023',
        '2024' => '2024',
        '2025' => '2025',
    ],
    'month' => [
        '1' => 'JAN',
        '2' => 'FEB',
        '3' => 'MAR',
        '4' => 'APR',
        '5' => 'MAY',
        '6' => 'JUN',
        '7' => 'JUL',
        '8' => 'AUG',
        '9' => 'SEP',
        '10' => 'OCT',
        '11' => 'NOV',
        '12' => 'DEC',
    ],
    'month_names' => [
        '1' => 'January',
        '2' => 'February',
        '3' => 'March',
        '4' => 'April',
        '5' => 'May',
        '6' => 'June',
        '7' => 'July',
        '8' => 'August',
        '9' => 'September',
        '10' => 'October',
        '11' => 'November',
        '12' => 'December',
    ],
    'available_months' => ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec',
    ],
    'userskill_rating' => [
        '1' => '1-basic',
        '2' => '2-proficient',
        '3' => '3-advanced',
        '4' => '4-expert',
    ],
    'usercert_rating' => [
        '1' => 'yes',
    ],
    'defaultRole' => 'User',
    'activity_status' => [
        'active' => 'active',
        'inactive' => 'inactive',
    ],
    'users-mc' => [
        'DLP30' => 'DLP30',
        'DPS22' => 'DPS22',
        'DMR03' => 'DMR03',
        'DPS26' => 'DPS26',
    ],
    'action_status' => [
        'OPEN' => 'OPEN',
        'CLOSED' => 'CLOSED',
        'ON HOLD' => 'ON HOLD',
        'IN IMPLEMENTATION' => 'IN IMPLEMENTATION',
    ],
    'action_severity' => [
        'LOW' => 'LOW',
        'MEDIUM' => 'MEDIUM',
        'TOP' => 'TOP',
    ],

];
