<?php

return [
    'employee_type' => [
        '' => '',
        'Employee' => 'Employee',
        'Contractor' => 'Contractor',
        'External Worker'=>'External Worker',
        'Affiliate Worker'=>'Affiliate Worker'

    ],
    'loe_type' => [
        'Consultant'=>'Consultant',
        'Senior Consultant'=>'Senior Consultant',
        'Managing Consultant'=>'Managing Consultant',
        'Managing Business Consultant'=>'Managing Business Consultant'
    ],
    'region' => [
        '' => '',
        'Europe' => 'Europe',
        'MEA' => 'MEA',
        'NAM' => 'NAM',
        'LATAM' => 'LATAM',
        'APAC' => 'APAC',
        'Russia' => 'Russia',
        'Emerging Markets'=>'Emerging Markets',
        'Asia Pacific'=>'Asia Pacific',
        'North America'=>'North America',
        'France'=>'France',
    ],
    'job_role' => [
        '' => '',
        'ASC' => 'ASC',
        'ISC' => 'ISC',
        'Management'=>'Management',
        'Integration'=>'Integration',
        'Advisory'=>'Advisory',
        'Business'=>'Business',
    ],
    'domain-users' => [
        '' => '',
        'APM' => 'APM',
        'Security' => 'Security',
        'SDLAN' => 'SDLAN',
        'SDWAN' => 'SDWAN',
        'UC' => 'UC',
        'CC' => 'CC',
        'SMS' => 'SMS',
        'DD' => 'DD',
    ],
    'domain-projects' => [
        'Hybrid Security' => 'Hybrid Security',
        'Hybrid APM' => 'Hybrid APM',
        'Hybrid Network' => 'Hybrid Network',
        'UC' => 'UC',
    ],
    'meta_activity' => [
        'BILLABLE' => 'BILLABLE',
        'ABS' => 'ABS',
        'OTHER' => 'OTHER',
        'CF' => 'CF',
    ],
    'project_status' => [
        'Pipeline' => 'Pipeline',
        'Started' => 'Started',
        'Closed' => 'Closed',
    ],
    'project_type' => [
        'Baseline' => 'Baseline',
        'Project' => 'Project',
        'Pre-sales' => 'Pre-sales',
        'Orange absence or other' => 'Orange absence or other',
    ],
    'project_subtype' => [
        'POC' => 'POC',
        'Assessment' => 'Assessment',
        'Pilot' => 'Pilot',
        'Build/Run' => 'Build/Run',
        'Recurring consulting' => 'Recurring consulting',
        'OpenLab' => 'OpenLab',
    ],
    'samba_stage' => [
        '1 Pre-Qualification' => '1 Pre-Qualification',
        '2 Qualification' => '2 Qualification',
        '3 Proposal' => '3 Proposal',
        '4 Negotiation' => '4 Negotiation',
        '5 Handover' => '5 Handover',
        'Closed Cancelled' => 'Closed Cancelled',
        'Closed Duplicate' => 'Closed Duplicate',
        'Closed Lost' => 'Closed Lost',
        'Closed Won' => 'Closed Won',
    ],
    'activity_type' => [
        '' => '',
        'ISC' => 'ISC',
        'ASC' => 'ASC',
    ],
    'year' => [
        '2017' => '2017',
        '2018' => '2018',
        '2019' => '2019',
        '2020' => '2020',
        '2021' => '2021',
        '2022' => '2022',
        '2023' => '2023',
        '2024' => '2024',
        '2025' => '2025',
    ],
    'month' => [
        '1' => 'JAN',
        '2' => 'FEB',
        '3' => 'MAR',
        '4' => 'APR',
        '5' => 'MAY',
        '6' => 'JUN',
        '7' => 'JUL',
        '8' => 'AUG',
        '9' => 'SEP',
        '10' => 'OCT',
        '11' => 'NOV',
        '12' => 'DEC',
    ],
    'month_names' => [
        '1' => 'January',
        '2' => 'February',
        '3' => 'March',
        '4' => 'April',
        '5' => 'May',
        '6' => 'June',
        '7' => 'July',
        '8' => 'August',
        '9' => 'September',
        '10' => 'October',
        '11' => 'November',
        '12' => 'December',
    ],
    'available_months' => [
        '1' => 'jan',
        '2' => 'feb',
        '3' => 'mar',
        '4' => 'apr',
        '5' => 'may',
        '6' => 'jun',
        '7' => 'jul',
        '8' => 'aug',
        '9' => 'sep',
        '10' => 'oct',
        '11' => 'nov',
        '12' => 'dec',
    ],
    'available_months_h1' => [
        'jan',
        'feb',
        'mar',
        'apr',
        'may',
        'jun',
    ],
    'available_months_h2' => [
        'jul',
        'aug',
        'sep',
        'oct',
        'nov',
        'dec',
    ],
    'userskill_rating' => [
        '1' => '1-basic',
        '2' => '2-proficient',
        '3' => '3-advanced',
        '4' => '4-expert',
    ],
    'usercert_rating' => [
        '1' => 'yes',
    ],
    'defaultRole' => 'User',
    'activity_status' => [
        '' => '',
        'active' => 'active',
        'inact.' => 'inact.',
    ],
    'users-mc' => [
        'DLP30' => 'DLP30',
        'DPS22' => 'DPS22',
        'DMR03' => 'DMR03',
        'DPS26' => 'DPS26',
        'DPS32' => 'DPS32',
        'DPS72' => 'DPS72',
        'DPS52' => 'DPS52',
        'DPS62' => 'DPS62',
        'DPS92' => 'DPS92',
        'DPS42' => 'DPS42',
        'DRU13' => 'DRU13',
        'SRU13' => 'SRU13',
        'DPS37' => 'DPS37',
        'DPS67' => 'DPS67',
        'DPS57' => 'DPS57',
        'DPS27' => 'DPS27',
        'DPS97' => 'DPS97',
        'DPS47' => 'DPS47',
        'DAS58' => 'DAS58',
        'DCB58' => 'DCB58',
        'DCE58' => 'DCE58',
        'DCS58' => 'DCS58',
        'DCV15' => 'DCV15',
        'DCV25' => 'DCV25',
        'DGM58' => 'DGM58',
        'DGS23' => 'DGS23',
        'DGS25' => 'DGS25',
        'DLP30' => 'DGS25',
        'DMR03' => 'DGS25',
        'DMR58' => 'DMR58',
        'DPP20' => 'DMR58',
        'DPS22' => 'DPS22',
        'DPS42' => 'DPS42',
        'DPS52' => 'DPS52',
        'DPS54' => 'DPS52',
        'DRU13' => 'DRU13',
        'DSE01' => 'DRU13',
        'DSP58' => 'DRU13',
        'DSS40' => 'DSS40',
        'DXX33' => 'DXX33',
        'GHG01' => 'GHG01',
        'SCC02' => 'SCC02',
        'SCC03' => 'SCC03',
        'SCC05' => 'SCC05',
        'SGC10' => 'SGC10',
        'SIS10' => 'SIS10',
        'SMR21' => 'SMR21',
        'SPG56' => 'SPG56',
        'SPG64' => 'SPG64',
        'SPS31' => 'SPS31',
        'SPS32' => 'SPS32',
        'SPV02' => 'SPV02',
        'SSM34' => 'SSM34',
        'SPI02' => 'SPI02',
        'OCF22' => 'OCF22',
        'DMR03' => 'DMR03',
        'OMR01' => 'OMR01',
        'DSE01' => 'OMR01',
        'SGM23' => 'SGM23',
        'DPS45' => 'DPS45',
        'DPP20' => 'DPP20',
        'SPS76' => 'SPS76',
        'DPL94' => 'DPL94',
        'DPS54' => 'DPL94',
        'DSP58' => 'DSP58',
        'GIM58' => 'GIM58',
        'SGM51' => 'SGM51',
        'SGM54' => 'SGM54',
        'SGM55' => 'SGM55',
        'SGM59' => 'SGM59',
        'DLP42' => 'DLP42',
        'DLP30' => 'DLP30',           
        'SEG14' => 'SEG14',
        'SPS23' => 'SPS23',
    ],
    'action_status' => [
        'OPEN' => 'OPEN',
        'CLOSED' => 'CLOSED',
        'ON HOLD' => 'ON HOLD',
        'IN IMPLEMENTATION' => 'IN IMPLEMENTATION',
    ],
    'action_severity' => [
        'LOW' => 'LOW',
        'MEDIUM' => 'MEDIUM',
        'TOP' => 'TOP',
    ],
    'loe_stage' => [
        'BUILD' => 'BUILD',
        'RUN' => 'RUN'
    ],

];
